---
title: "Statistical Thinking for the 21st Century 面向21世纪的统计思维"
author: "© 2019 Russell A. Poldrack 版权所有；由何凌锋编辑与翻译、林泽正审阅与校正"
date: "根据Draft: 2022-11-04译出"
knit: "bookdown::render_book"
bibliography: ["psych10-book.bib"]
biblio-style: "apalike"
documentclass: book
link-citations: yes
github-repo: poldrack/psych10-book
description: "A book about statistics."
always_allow_html: yes
fontsize: 12pt
monofont: "Source Code Pro"
monofontoptions: "Scale=0.7"
output:
  bookdown::pdf_book:
    keep_tex: yes
  bookdown::gitbook:
    lib_dir: "book_assets"
    config:
      edit: https://github.com/Hedaozi/statsthinking21-core/edit/bilingual/%s
    includes:
      in_header:
        - google_analytics.html
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=6, fig.height=6, #echo=FALSE, 
                      warning=FALSE, message=FALSE)
```

# Preface 前言 {-}

## 译者的话

翻译本书的目的有二，其一为借此契机让自己通读本书，其二为为致力于学习统计学、但阅读英文书籍尚有困难的学子提供一个可读的译本。本书的源代码见于[https://github.com/Hedaozi/statsthinking21-core](https://github.com/Hedaozi/statsthinking21-core)。若有任何意见与建议，烦请邮件至 hedaozi_amoy@outlook.com，或在Github仓库留言。感激不尽。

以下所有内容遵照原文：

<hr>

The goal of this book is to the tell the story of statistics as it is used today by researchers around the world.  It's a different story than the one told in most introductory statistics books, which focus on teaching how to use a set of tools to achieve very specific goals.  This book focuses on understanding the basic ideas of *statistical thinking* --- a systematic way of thinking about how we describe the world and use data make decisions and predictions, all in the context of the inherent uncertainty that exists in the real world. It also brings to bear current methods that have only become feasible in light of the amazing increases in computational power that have happened in the last few decades. Analyses that would have taken years in the 1950's can now be completed in a few seconds on a standard laptop computer, and this power unleashes the ability to use computer simulation to ask questions in new and powerful ways.

本书致力于在统计学被世界各地的研究人员普遍使用的当下讲述统计学的故事。本书所要讲述的故事与大多数统计学入门书籍中讲述的故事不同：后者侧重于教授如何使用一套工具来实现非常具体的目标，而本书旨在帮助读者理解“统计思维”（*statistical thinking*）的基本思想——一种系统的、思考我们如何在存在固有不确定性的真实世界中描述世界与使用数据做出决策和预测的思维方式。本书同样为读者带来了当代的、只有凭依几十年来不断爆发式增长的算力才能够实现的方法。在20世纪50年代需要花费数年时间完成的分析，现在仅需几秒钟就能在一台标准的笔记本电脑上完成。这种能量释放了使用计算机模拟以提出更新颖、更有力的问题的能力。

The book is also written in the wake of the reproducibility crisis that has engulfed many areas of science since 2010.  One of the important roots of this crisis is found in the way that statistical hypothesis testing has been used (and abused) by researchers (as I detail in the final chapter of the book), and this ties directly back to statistical education.  Thus, a goal of the book is to highlight the ways in which current statistical methods may be problematic, and to suggest alternatives.

另一方面，本书也是在2010年以来困扰诸多科学领域的复现危机的背景下写作的。正如我将要在本书的最后一章详细叙述的那样，这场危机的源头之一之一，就根植于统计学假设检验被研究者使用（和滥用）的方式之中。因此，本书同样旨在强调当代统计学的可能隐患，并提出替代方案。

## Why does this book exist? 本书何以存在？

In 2018 I began teaching an undergraduate statistics course at Stanford (Psych 10/Stats 60).  I had never taught statistics before, and this was a chance to shake things up.  I have been increasingly unhappy with undergraduate statistics education in psychology, and I wanted to bring a number of new ideas and approaches to the class.  In particular, I wanted to bring to bear the approaches that are increasingly used in real statistical practice in the 21st century.  As Brad Efron and Trevor Hastie laid out so nicely in their book "Computer Age Statistical Inference: Algorithms, Evidence, and Data Science", these methods take advantage of today's increased computing power to solve statistical problems in ways that go far beyond the more standard methods that are usually taught in the undergraduate statistics course for psychology students.

2018年，我开始在斯坦福大学教授一门面向本科生的统计学课程（Psych 10/Stats 60）。在此之前，我从未教授过统计学。因而，这门课程于我而言也是一个改变现状的契机：我对心理学的本科统计教育愈发不满，并想要将新的想法和方法带到课堂上，特别是那些在21世纪统计实践中被使用得越来越多的方法。正如Brad Efron与Trevor Hastie在《计算机时代的统计推断：算法、证据与数据科学》（Computer Age Statistical Inference: Algorithms, Evidence, and Data Science）中所阐述的那样，这些方法利用当下日益增强的算力来解决统计问题，远远超出了通常在心理学本科生统计课程中教授的更标准的方法。

The first year that I taught the class, I used Andy Field's amazing graphic novel statistics book, "An Adventure in Statistics", as the textbook.  There are many things that I really like about this book -- in particular, I like the way that it frames statistical practice around the building of models, and treats null hypothesis testing with sufficient caution. Unfortunately, many of my students disliked the book (except for the English majors, who loved it!), primarily because it involved wading through a lot of story to get to the statistical knowledge.  I also found it wanting because there are a number of topics (particularly those from the burgeoning field of artificial intelligence known as *machine learning*) that I wanted to include but were not discussed in his book.  I ultimately came to feel that the students would be best served by a book that follows very closely to my lectures, so I started writing down my lectures into a set of computational notebooks that would ultimately become this book. The outline of this book follows roughly that of Field's book, since the lectures were originally based in large part on the flow of that book, but the content is substantially different (and almost certainly much less fun and clever). I also tailored this book for the 10-week quarter system that we use at Stanford, which provides less time than the 16-week semester that most statistical textbooks are built for.  

在我教授这门课的第一年，我将Andy Field神奇的统计学图像小说《统计学的冒险》作为教材。 这本书有很多我非常喜欢的地方，特别是围绕着模型建立的统计实践，以及对待虚无假设检验地谨慎态度。不幸的是，由于需要通过故事来获取统计知识，我的许多学生并不喜欢这本书（除了英语专业的学生，他们很喜欢！）。我也发现这本书令我有所失望，有些我想包括在课程中的主题并未在书中被讨论（特别是来自新兴的人工智能领域的机器学习）。最终，我觉得一本紧跟我的课程的书对学生而言是最好的。因此，我开始将讲义以一系列电子笔记本写下，最终形成本书。由于课程内容最初在很大程度上基于Field的书的流程，本书的大纲也大致遵循了Field的书，但本书的内容却有很大不同（几乎可以肯定的是，本书要比Field的书无趣得多）。此外，这本书是为斯坦福大学所使用的10个星期的学季制度量身定做的，因而短于适用于16周学期的大多数统计教材。

## The golden age of data 数据的黄金时代

Throughout this book I have tried when possible to use examples from real data.  This is now very easy because we are swimming in open datasets, as governments, scientists, and companies are increasingly making data freely available.  I think that using real datasets is important because it prepares students to work with real data rather than toy datasets, which I think should be one of the major goals of statistical training. It also helps us realize (as we will see at various points throughout the book) that data don't always come to us ready to analyze, and often need *wrangling* to help get them into shape.  Using real data also shows that the idealized statistical distributions often assumed in statistical methods don't always hold in the real world -- for example, as we will see in Chapter \@ref(summarizing-data), distributions of some real-world quantities (like the number of friends on Facebook) can have very long tails that can break many standard assumptions.  

在本书中，我尽可能地将真实数据作为例子。由于政府、科学家和企业正在越来越多地提供免费获取的数据，这在当下并不难实现。我认为，使用真实的数据集非常重要，因为它让学生准备好与真实数据而非玩具数据打交道——我认为这应该是统计培训的主要目标之一。正如我们将在本书的不同地方多次看到的那样，它还能帮助我们认识到数据并不总是随时可以分析的，而是往往需要先经过“处理”（wrangling）成型的。使用真实数据也为学生表明，统计方法中经常假设的理想化统计分布在现实世界中并不总是成立的。例如，正如我们将在第\@ref(summarizing-data)章中看到的，一些现实世界中的数量（如Facebook上的朋友数量）的分布可能有很长的尾巴，足以打破许多标准假设。

I apologize up front that the datasets are heavily US-centric.  This is primarily because the best dataset for many of the demonstrations is the National Health and Nutrition Examination Surveys (NHANES) dataset that is available as an R package, and because many of the other complex datasets included in R (such as those in the `fivethirtyeight` package) are also based in the US.  If you have suggestions for datasets from other regions, please pass them along to me!

我首先为本书使用的数据集大多以美国为中心这件事儿道歉。这主要是因为许多演示的最佳数据集是国家健康和营养检查调查（the National Health and Nutrition Examination Surveys，NHANES）（该数据集可作为R包获取），也因为R中的许多其他数据集（例如`fivethirtyeight`包中的）也是同样基于美国。如果你对来自其他区域的数据集有所建议，请将它们传给我！

## The importance of doing statistics 做统计的重要性

The only way to really learn statistics is to *do* statistics.  While historically many statistics courses were taught using point-and-click statistical software, it is increasingly common for statistical education to use open-source languages in which students can code their own analyses.  I think that being able to code one's analyses is essential in order to gain a deep appreciation for statistical analysis, which is why the students in my course at Stanford are expected to learn to use the R statistical programming language to analyze data, alongside the theoretical knowledge that they learn from this book.  

真正学习统计学的唯一方法是“做”统计。尽管虽然历史上许多统计学课程是使用点选式统计软件进行教学的，但统计学教育越来越普遍地使用开源语言，学生可以在其中编写自己的分析报告。我认为，为了深入了解统计分析，使用编程完成数据分析的能力是必不可少的。这也是为什么在我的课程上，学生们被期望在学习理论知识的同时，还要学会使用R语言来分析数据。 

There are two online companions to this textbook that can help the reader get started learning to program; [one focuses on the R programming language](https://statsthinking21.github.io/statsthinking21-R-site/), and [another focuses on the Python language](https://statsthinking21.github.io/statsthinking21-python/).  Both are currently works in progress -- please feel free to contribute!

本书有两个帮助读者开始学习编程的线上配套资源，[其中一个使用R语言编程](https://statsthinking21.github.io/statsthinking21-R-site/)，而[另一个使用Python语言编程](https://statsthinking21.github.io/statsthinking21-python/)。这两项资源都仍是进行时，请随意贡献自己的力量！


## An open source book 一本开源的书

This book is meant to be a living document, which is why its source is available online at [https://github.com/statsthinking21/statsthinking21-core](https://github.com/statsthinking21/statsthinking21-core).  If you find any errors in the book or want to make a suggestion for how to improve it, please open an issue on the Github site. Even better, submit a pull request with your suggested change.  

本书旨在成为一本不断更新的文档，这就是为什么我将源码公开在[https://github.com/statsthinking21/statsthinking21-core](https://github.com/statsthinking21/statsthinking21-core)。如果你发现书中有任何错误，或者想对如何改进它提出建议，请在Github上开一个Issue。更好的是，提交一个包括修改建议的pull request。

The book is licensed according to the [Creative Commons Attribution-NonCommercial 2.0 Generic (CC BY-NC 2.0) License](https://creativecommons.org/licenses/by-nc/2.0/).  Please see the terms of that license for more details.

本书根据[Creative Commons Attribution-NonCommercial 2.0 Generic (CC BY-NC 2.0) License](https://creativecommons.org/licenses/by-nc/2.0/)授权。详情请见该许可证的条款。

## Acknowledgements 致谢

I'd first like to thank Susan Holmes, who first inspired me to consider writing my own statistics book.  Anna Khazenzon provided early comments and inspiration.  Lucy King provided detailed comments and edits on the entire book, and helped clean up the code so that it was consistent with the Tidyverse.  Michael Henry Tessler provided very helpful comments on the Bayesian analysis chapter. Particular thanks also go to Yihui Xie, creator of the Bookdown package, for improving the book's use of Bookdown features (including the ability for users to directly generate edits via the Edit button).  Finally, Jeanette Mumford provided very helpful suggestions on the entire book.

我首先要感谢Susan Holmes，是她第一次启发我考虑写自己的统计书。Anna Khazenzon提供了早期的评论和灵感。Lucy King对整本书提供了详细的评论和编辑，并帮助清理了代码，使其与Tidyverse一致。Michael Henry Tessler对贝叶斯分析章节提供了非常有用的意见。还要特别感谢Bookdown软件包的创建者谢毅辉，他改进了本书对Bookdown功能的使用（包括让用户通过编辑按钮直接生成编辑）。最后，Jeanette Mumford对整本书提供了非常有益的建议。

I'd also like to thank others who provided helpful comments and suggestions: Athanassios Protopapas, Wesley Tansey, Jack Van Horn, Thor Aspelund.

我还要感谢其他提供有益意见和建议的人：Athanassios Protopapas、Wesley Tansey、Jack Van Horn，以及Thor Aspelund。

Thanks to the following Twitter users for helpful suggestions: \@enoriverbend

感谢以下Twitter用户的有益建议：\@enoriverbend

Thanks to the following individuals who have contributed edits or issues by Github or email: 
Isis Anderson, Larissa Bersh, Isil Bilgin, Forrest Dollins, Chuanji Gao, Nate Guimond, Alan He, Wu Jianxiao, James Kent, Dan Kessler, Philipp Kuhnke, Leila Madeleine, Lee Matos, Ryan McCormick, Jarod Meng, Kirsten Mettler, Shanaathanan Modchalingam, Martijn Stegeman, Mehdi Rahim, Jassary Rico-Herrera, Mingquian Tan, Wenjin Tao, Laura Tobar, Albane Valenzuela, Alexander Wang, Michael Waskom, 
barbyh, basicv8vc, brettelizabeth, codetrainee, dzonimn, epetsen, carlosivanr, hktang, jiamingkong, khtan, kiyofumi-kan, NevenaK, ttaweel.

感谢以下通过Github或电子邮件提供编辑或问题的个人：
Isis Anderson, Larissa Bersh, Isil Bilgin, Forrest Dollins, Chuanji Gao, Nate Guimond, Alan He, Wu Jianxiao, James Kent, Dan Kessler, Philipp Kuhnke, Leila Madeleine, Lee Matos, Ryan McCormick, Jarod Meng, Kirsten Mettler, Shanaathanan Modchalingam, Martijn Stegeman, Mehdi Rahim, Jassary Rico-Herrera, Mingquian Tan, Wenjin Tao, Laura Tobar, Albane Valenzuela, Alexander Wang, Michael Waskom, 
barbyh, basicv8vc, brettelizabeth, codetrainee, dzonimn, epetsen, carlosivanr, hktang, jiamingkong, khtan, kiyofumi-kan, NevenaK, ttaweel.

Special thanks to Isil Bilgin for assistance in fixing many of these issues.  

特别感谢Isil Bilgin协助修复了Issues中的许多问题。
